# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/CHANGE_ME/cdm_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2026-08-18-r3"

containerPort: 5000

config:
  KAFKA_HOST: "CHANGE_ME"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "CHANGE_ME"
  KAFKA_CONSUMER_PASSWORD: "CHANGE_ME"
  KAFKA_CDM_CONSUMER_GROUP: "cdm-service-consumer-group"
  KAFKA_DDS_SERVICE_ORDERS_TOPIC: "dds-service-orders"

  PG_WAREHOUSE_HOST: "CHANGE_ME.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "CHANGE_ME"
  PG_WAREHOUSE_USER: "CHANGE_ME"
  PG_WAREHOUSE_PASSWORD: "CHANGE_ME"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
